In [4]:
import pandas as pd

training = pd.read_csv('cf_data/training_stars.csv')
training.sample(50)

,source_paper,star_name,source_id,ra,dec,pmra,pmdec,prot_days,age_gyr,age_err_lo_gyr,...,twomass_id,k_m,k_cmsig,A_Ks,A_Ks_err,k_m_0,M_Ks,flag_outside_mann_range,mass_msun,mass_msun_err
4663,MOCADB,Gaia DR2 2932602127825178240,2932602127825178240,106.434182,-19.512050,NaN,NaN,2.214220,0.028800,0.003300,...,07054420-1930434,12.879,0.041,0.008840,0.000453,12.870160,4.618244,False,0.656880,0.017983
2634,MOCADB,Cl* Melotte 22 DH 852,65338688937033344,59.383427,22.433195,NaN,NaN,0.409500,0.127400,0.010000,...,03573200+2226002,12.340,0.023,0.023244,0.009906,12.316756,6.583477,False,0.349598,0.024288
6282,multi,Antares,6050564834995573632,244.849686,-22.344913,-11.488946,-25.458438,1.399000,0.012650,NaN,...,16192393-2220412,11.901,0.020,0.015565,0.000849,11.885435,6.346094,False,0.387452,0.009655
1904,MOCADB,Gaia DR3 4066069114228532480,4066069114228532480,271.105271,-24.337357,NaN,NaN,1.936920,0.005500,0.000600,...,18042526-2420144,12.254,0.033,0.054628,0.002801,12.199372,1.476128,True,NaN,NaN
5441,multi,NGC2516,5290710903297630336,118.926204,-61.068603,-5.154445,11.250052,3.619000,0.263000,NaN,...,07554231-6104071,14.332,0.075,0.033901,0.001751,14.298099,6.210064,False,0.409339,0.020981
2540,MOCADB,Gaia DR3 4065970737974382208,4065970737974382208,271.164652,-24.456673,NaN,NaN,3.807400,0.005500,0.000600,...,18043951-2427240,12.863,0.062,0.057132,0.002968,12.805868,1.948527,True,NaN,NaN
5136,D+19,Hyades,3314581984953794816,67.254754,18.673540,113.322459,-36.057666,1.540000,0.775000,NaN,...,04290099+1840254,8.690,0.019,0.000000,0.000000,8.690000,5.512002,False,0.523589,0.012528
1276,MOCADB,EPIC 211726170,657982392677845120,129.379433,16.269744,NaN,NaN,0.467000,0.617000,0.010000,...,08373109+1616111,14.305,0.063,0.002063,0.000107,14.302937,7.900512,False,0.186360,0.009520
3477,MOCADB,Gaia DR3 3051566880768262400,3051566880768262400,105.654664,-8.262005,NaN,NaN,2.904000,0.144500,NaN,...,07023709-0815426,16.587,NaN,0.044904,0.014464,16.542096,6.648494,False,NaN,NaN
5960,R+18,NSco,6245698393390305664,243.009915,-19.439496,-9.339760,-24.963318,1.777200,0.006000,NaN,...,16120239-1926218,10.856,0.021,0.027362,0.001419,10.828638,5.091476,False,0.588413,0.014648
3943,MOCADB,EPIC 203072076,6042468787283782656,243.043777,-27.355277,NaN,NaN,0.359000,0.015000,0.010000,...,16121053-2721184,11.689,0.023,0.003699,0.000203,11.685301,6.514534,False,0.360695,0.008981
7005,F+20,NGC2516,5290668778258672128,119.635758,-60.996034,-4.685742,11.650333,4.287000,0.263000,NaN,...,07583259-6059458,13.068,0.038,0.025419,0.001305,13.042581,4.997182,False,0.602283,0.016055
5630,multi,ROph_L1688,6046072986395944064,247.266349,-24.861632,-8.347800,-25.341680,1.234250,0.003700,NaN,...,16290392-2451414,10.735,0.019,0.013466,0.001416,10.721534,5.009946,False,0.600448,0.015090
1144,MOCADB,Gaia DR2 5586739153354818432,5586739153354818432,115.082108,-38.264155,NaN,NaN,3.720000,0.100000,0.045000,...,07401971-3815532,11.236,0.030,0.001895,0.000100,11.234105,4.734954,False,0.640206,0.016196
2740,MOCADB,Gaia DR3 3426267416870187392,3426267416870187392,92.182928,24.233636,NaN,NaN,2.577000,0.950000,0.670000,...,06084388+2414010,15.120,0.104,0.039414,0.009263,15.080586,5.785167,False,0.474703,0.058846
5323,F+21,NGC3532,5339401126517113472,167.329148,-58.760010,-10.780212,5.058586,12.953600,0.398000,NaN,...,11091902-5845361,13.004,0.029,0.007661,0.000393,12.996339,4.644338,False,0.653178,0.016787
1999,MOCADB,Gaia DR2 507202377434774016,507202377434774016,31.401391,60.023074,NaN,NaN,0.790992,0.398100,0.079600,...,02053632+6001231,13.298,0.040,0.055283,0.004693,13.242717,5.330949,False,0.551923,0.016340
282,Mamonova2025,2MASS J12313807-4558593,6132146982868270976,187.908304,-45.983276,NaN,NaN,1.834000,0.010000,0.003000,...,12313807-4558593,8.412,0.029,0.002052,0.000105,8.409948,3.888889,True,NaN,NaN
4219,MOCADB,DANCe J03391022+1955305,57311566858308736,54.792603,19.925073,NaN,NaN,1.799900,0.127400,0.010000,...,03391020+1955310,12.214,0.023,0.017008,0.001262,12.196992,6.466910,False,0.368203,0.009297
2960,MOCADB,2MASS J06381055-8402450,5194120112463898496,99.543776,-84.045611,NaN,NaN,2.823200,0.133000,0.010000,...,06381055-8402450,9.860,0.020,0.000000,0.000000,9.860000,5.888907,False,0.462366,0.010923
585,MOCADB,Gaia DR2 5239857283625105920,5239857283625105920,160.935403,-64.118434,NaN,NaN,2.780000,0.040000,0.001400,...,10434454-6407064,11.534,0.025,0.006541,0.000344,11.527459,5.648806,False,0.501577,0.012236
6963,M+11,M34,337150676425488256,40.471867,42.590612,1.568282,-5.813117,0.880000,0.161000,NaN,...,02415324+4235262,12.917,0.030,0.013003,0.000668,12.903997,4.515107,False,0.671677,0.018466
6575,GR+21,Praesepe,665412690396632832,127.804459,20.900070,-33.057662,-13.919678,18.423300,0.718000,NaN,...,08311310+2054003,12.798,0.027,0.002277,0.000117,12.795723,6.384155,False,0.381333,0.010485
4006,MOCADB,Gaia DR2 47116517089271168,47116517089271168,61.102250,18.343376,NaN,NaN,2.678690,0.028000,0.007000,...,04042453+1820364,11.884,0.020,0.001673,0.000087,11.882327,6.721743,False,0.328955,0.007996
4360,MOCADB,Gaia DR3 507492927682638080,507492927682638080,34.877952,60.943861,NaN,NaN,0.325559,0.031623,0.021623,...,02193069+6056378,14.009,0.058,0.062581,0.003386,13.946419,5.532750,False,0.519591,0.024221
2236,MOCADB,Gaia DR2 258711791780837760,258711791780837760,67.686891,49.376068,NaN,NaN,0.616199,0.115000,0.092000,...,04304482+4922345,11.794,0.022,0.001523,0.000080,11.792477,6.479185,False,0.366249,0.008985
707,MOCADB,NQ Tau,65299965511216384,56.165142,24.528764,NaN,NaN,0.609960,0.127400,0.010000,...,03443961+2431442,11.881,0.024,0.008931,0.001203,11.872069,6.224812,False,0.407116,0.010080
3700,MOCADB,Gaia DR2 64925444363253632,64925444363253632,57.421489,23.249687,NaN,NaN,0.197100,0.127400,0.010000,...,03494112+2314596,13.064,0.030,0.003731,0.001115,13.060269,7.481201,False,0.228696,0.008846
3903,MOCADB,Gaia DR2 5903188181897560832,5903188181897560832,226.028697,-48.857514,NaN,NaN,4.316620,0.015000,0.010000,...,15040691-4851267,10.012,0.023,0.001537,0.000079,10.010463,4.713523,False,0.643289,0.015793
1246,MOCADB,Gaia DR2 4054313994889362304,4054313994889362304,265.206480,-32.190647,NaN,NaN,2.743200,0.105000,0.020000,...,17404955-3211263,12.620,NaN,0.034125,0.001779,12.585875,4.343584,True,NaN,NaN
6165,multi,DSco,6237148384817470336,239.474372,-23.298229,-13.865121,-23.534467,2.150000,0.010150,NaN,...,15575386-2317531,11.315,0.021,0.029688,0.001544,11.285312,5.519761,False,0.522339,0.012757
347,Mamonova2025,2MASS J21464282-8543046,6342940473056949120,326.691927,-85.718780,NaN,NaN,0.850000,0.024000,0.003000,...,21464282-8543046,7.991,0.024,0.000000,0.000000,7.991000,7.031779,False,0.284613,0.007082
2046,MOCADB,Gaia DR2 507120193240918272,507120193240918272,32.396815,59.568235,NaN,NaN,0.872539,0.414000,0.023000,...,02093526+5934057,12.742,0.031,0.005808,0.000336,12.736192,6.683511,False,0.334666,0.009613
441,MOCADB,Gaia DR2 3406352826045301632,3406352826045301632,71.613500,17.626496,NaN,NaN,1.690000,0.695000,0.067000,...,04462712+1737359,10.618,0.018,0.000000,0.000000,10.618000,7.315715,False,0.248028,0.006200
3981,MOCADB,2MASS J15415562-2538465,6235077798261346688,235.481677,-25.646373,NaN,NaN,1.404000,0.015000,0.010000,...,15415562-2538465,12.233,0.024,0.011928,0.001234,12.221072,6.417521,False,0.376001,0.010118
667,MOCADB,Gaia DR2 5514369229297398400,5514369229297398400,122.657484,-49.169963,NaN,NaN,1.251000,0.034900,0.001200,...,08103780-4910118,13.754,0.052,0.007579,0.000434,13.746421,5.962104,False,0.450123,0.017359
6576,multi,Praesepe,665454368759275520,128.557699,21.397788,-35.177548,-14.833035,1.560000,0.718000,NaN,...,08341389+2123521,13.297,0.036,0.002444,0.000126,13.294556,6.905335,False,0.302175,0.010541
1270,MOCADB,Gaia DR2 5587029179605935744,5587029179605935744,114.471486,-37.329049,NaN,NaN,1.820000,0.036300,0.007260,...,07375317-3719447,12.773,0.033,0.001859,0.000097,12.771141,6.233603,False,0.405706,0.010998
340,LWRD,2MASS J21154192+1746242,1785074513721959552,318.924975,17.773430,NaN,NaN,9.020000,0.328000,0.033000,...,21154192+1746242,9.040,0.023,0.001478,0.000077,9.038522,4.760903,False,0.636421,0.018019
5909,multi,SSco,6049830876625048320,242.025401,-24.718436,-10.333419,-23.788222,1.293300,0.010250,NaN,...,16080610-2443059,11.527,0.023,0.018833,0.001067,11.508167,5.553336,False,0.516963,0.012906
1061,MOCADB,Gaia DR3 2068349876303403904,2068349876303403904,304.746409,40.706272,NaN,NaN,1.276670,0.002000,NaN,...,20185913+4042225,12.887,0.051,0.072590,0.014444,12.814410,2.837325,True,NaN,NaN
6597,multi,DSco,6245669050173377280,242.545805,-19.767864,-11.713764,-22.973705,1.667300,0.010150,NaN,...,16101100-1946040,11.380,0.021,0.029319,0.001527,11.350681,5.637967,False,0.503342,0.012295
6137,multi,Praesepe,664323761568567808,129.763212,20.043709,-37.823417,-13.865086,13.518650,0.718000,NaN,...,08390321+2002376,11.051,0.020,0.002338,0.000120,11.048662,4.744467,False,0.638878,0.015656
4319,MOCADB,Gaia DR3 2019749297744908032,2019749297744908032,292.262426,23.724365,NaN,NaN,4.302593,0.003162,0.002162,...,19290298+2343277,12.856,0.048,0.109939,0.013022,12.746061,3.848429,True,NaN,NaN
1395,MOCADB,Gaia DR2 5338681839753910784,5338681839753910784,165.749431,-58.815735,NaN,NaN,10.481900,0.360000,0.020000,...,11025986-5848566,13.903,0.065,0.008202,0.000421,13.894798,5.569887,False,0.514158,0.018304
3142,MOCADB,Gaia DR3 4522208762895712768,4522208762895712768,276.997637,16.196056,NaN,NaN,4.727241,0.055000,0.026000,...,18275943+1611458,13.043,0.036,0.034224,0.001761,13.008776,5.340979,False,0.550382,0.015829
2357,MOCADB,Gaia DR2 65101606741121792,65101606741121792,55.358215,23.259813,NaN,NaN,0.538400,0.127400,0.010000,...,03412595+2315361,12.822,0.024,0.012209,0.003009,12.809791,7.142403,False,0.269874,0.007189
6541,multi,Pleiades,66911231083913600,57.807800,25.386302,19.438803,-46.520884,0.533733,0.097000,NaN,...,03511384+2523116,11.973,0.022,0.005102,0.000559,11.967898,6.341643,False,0.388176,0.009553
5366,GR+21,M37,3451205268301107456,88.215037,32.639595,1.862288,-6.041930,1.206122,0.446000,NaN,...,05525155+3238224,15.680,0.183,0.037879,0.009005,15.642121,6.204720,False,0.403835,0.083735
3777,MOCADB,Gaia DR2 237372332669785856,237372332670849920,53.659013,41.729589,NaN,NaN,1.193440,0.079000,0.002300,...,03343813+4143469,12.454,0.024,0.007863,0.000439,12.446137,6.615887,False,0.344950,0.009320

In [10]:
no_ks = pd.read_csv('cf_data/no_ks_flagged.csv')
no_ks

,catalog,gaiadr3_id,star_name,ra,dec,parallax,source_paper,BPRP0,likely_mdwarf
0,training_stars,4472832130942576128,Barnard's Star (GJ 699),269.448503,4.739420,546.975940,Engle2023,NaN,NaN
1,training_stars,4810594479418042368,Kapteyn's Star (GJ 191),77.959937,-45.043813,254.198593,Engle2023,NaN,NaN
2,training_stars,5239559011062184960,Gaia DR2 5239559011062184960,163.528362,-65.038598,6.471846,MOCADB,NaN,NaN
3,training_stars,243171706750419200,Gaia DR2 243171706750419200,51.622717,47.758138,5.596195,MOCADB,NaN,NaN
4,training_stars,5537621735560202752,Gaia DR2 5537621735560202752,117.884766,-39.794498,5.167912,MOCADB,NaN,NaN
...,...,...,...,...,...,...,...,...,...
440,cf_rotator_catalog,3051568392588578560,NaN,105.764390,-8.304798,0.304980,NaN,1.147766,False
441,cf_rotator_catalog,3050813406061551872,NaN,105.450355,-8.392770,0.914328,NaN,1.653479,True
442,cf_rotator_catalog,3451204929001311360,NaN,88.194800,32.603808,0.779809,NaN,2.007832,True
443,cf_rotator_catalog,5290816422049740800,NaN,119.680431,-60.695983,2.462537,NaN,1.958634,True
444,cf_rotator_catalog,5290823671959351936,NaN,120.025747,-60.588262,2.433409,NaN,1.092404,False